# Basic
title: Linyi (Leo) Ni
subtitle: 『师夷长技以自强』
welcome_message: <a href="https://nilinyi.github.io/" target="_blank">Welcome to my blog!</a>
description: An adventurous iOS deveploer in Silicon Valley.
creator: <a href="https://nilinyi.github.io/">@nilinyi</a>

url: "https://nilinyi.github.io/"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color:

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: LinkedIn, description: LinkedIn, url: 'https://www.linkedin.com/in/linyi-ni/'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo:

# Social
social:
    # weibo: nilinyi
    github: nilinyi
    # twitter: nilinyi
    # gplus: 107108267983477358170
    mail: nilinyi@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
